### ISSUE TITLE
CLI Console Prompting for Password

### ISSUE THREAD

**Issue by ncstate-mafields** [signal18/replication-manager#399] opened 2022-01-31 23:25 UTC
Historically, we have never had a password prompt when accessing the CLI console. It would simply drop straight into the console. 

Since upgrading to 2.2.10, we now get a password prompt before the console opens. 
We are not configuring an API password in the configuration. 

The issue is present in 2.2.10, 2.2.11, and 2.2.12. Only downgrading to 2.2.9 restores the previous functionality. 

Is there a way to avoid getting prompted for a password when accessing the CLI console in 2.2.10+?

**Comment by svaroqui** [comment] 2022-02-01 09:32
i'v push a new release that should help , API always used a password just that default is the same as the server api so it does not prompt , let me knwow if 2.2.14 fixes your issue , also can you let us know if you change the server api password ?

**Comment by svaroqui** [comment] 2022-02-14 07:49
Any news could this be close ?

**Comment by ncstate-mafields** [comment] 2022-02-14 18:55
I haven't been able to test quite yet. Having some issues getting my compiled RPM working on my production server. Will hopefully be able to build and test soon.

**Comment by svaroqui** [comment] 2022-02-15 07:29
Is this a new arm architecture ?

**Comment by svaroqui** [comment] 2022-02-15 07:32
The reason for this regression was found in usage introduction of a v3 native grpc api and i think it is fixed now

**Comment by ncstate-mafields** [comment] 2022-02-24 22:38
Confirmed that this is no longer an issue on v2.2.16

**Comment by svaroqui** [comment] 2022-02-25 14:29
Thanks happy clustering !

**Closed as completed by svaroqui** 2022-02-25 14:29 UTC
